# Generated by Django 5.2.11 on 2026-02-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_participant_question_questionchoice_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='requires_approval',
            field=models.BooleanField(default=True, help_text='Uncheck this to automatically approve all registrations.'),
        ),
    ]
