# Generated by Django 5.2.11 on 2026-02-25 05:00

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF Document'), ('image', 'Image'), ('video', 'Video Link'), ('other', 'Other File')], default='pdf', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to=core.models.resource_upload_path)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('unlock_time', models.DateTimeField(blank=True, help_text='Leave blank for immediate access', null=True)),
                ('requires_check_in', models.BooleanField(default=False, help_text='Require attendance before downloading')),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.event')),
                ('session', models.ForeignKey(blank=True, help_text='Leave blank for general event resources', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.session')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
